### ISSUE TITLE
cargo test need run with root 

### ISSUE THREAD

**Issue by AlexiaChen** [AlexiaChen/rocker#2]
because unit test need create cgroup directory for testing

**Comment by AlexiaChen** [comment]
add file in your project  `.cargo/config`:

```toml
[target.x86_64-unknown-linux-gnu]
runner = 'sudo -E'
```

quote from  https://github.com/rust-lang/cargo/issues/5999
